### Get all movies
GET http://localhost:3010/movies
Accept: application/json

### Add a new movie
POST http://localhost:3010/movies
Content-Type: application/json

{
    "title": "Apollo 13",
    "director": "Ron Howard",
    "year": 1995
}

### Get a movie by ID
# Replace <id> with the MongoDB _id from your database
GET http://localhost:3010/movies/674063d7b8d7c5d6174557ee
Accept: application/json

### Update a movie
# Replace <id> with the MongoDB _id from your database
PUT http://localhost:3010/movies/<id>
Content-Type: application/json

{
    "title": "Inception",
    "director": "Christopher Nolan",
    "year": 2010
}

### Delete a movie
# Replace <id> with the MongoDB _id from your database
DELETE http://localhost:3010/movies/<id>

### Filter movies by year
GET http://localhost:3010/movies?year=1999
Accept: application/json

### Combined filter by year and director
GET http://localhost:3010/movies?year=2010&director=Christopher%20Nolan
Accept: application/json
